fix: add Merge to allowable commit messages
This allows for default merge commits to occur without --no-verify

diff --git a/home/.git_hooks/commit-msg b/home/.git_hooks/commit-msg
--- a/home/.git_hooks/commit-msg
+++ b/home/.git_hooks/commit-msg
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
-if ! head -1 "$1" | grep -qE "^Merge" || ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid. Please follow the semantic commit guidelines" >&2
-    exit 1
+title=$(head -1 "$1")
+if ! ( echo "$title" | grep -qE "^Merge" ); then
+    if ! (echo "$title" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"); then
+        echo "Aborting commit. Your commit message is invalid. Please follow the semantic commit guidelines" >&2
+        exit 1
+    fi
 fi
 
 if ! which aspell > /dev/null; then
